### ISSUE TITLE
@thuongtruong1009

### ISSUE THREAD

**Issue by thuongtruong1009** [thuongtruong1009/Snake-Game-OOP#12]
@thuongtruong1009 
You should fix the link of sound and image, which should get in the internal source code. Because itn't be changed  when you change on the device.
It shoud put in .('./link-directed/....');

_Originally posted by @font-end-pro in https://github.com/thuongtruong1009/Snake-Game-OOP/discussions/5#discussioncomment-1144935_

**Comment by font-end-pro** [comment]
> @thuongtruong1009
> You should fix the link of sound and image, which should get in the internal source code. Because itn't be changed when you change on the device.
> It shoud put in .('./link-directed/....');
> 
> _Originally posted by @font-end-pro in [#5 (comment)](https://github.com/thuongtruong1009/Snake-Game-OOP/discussions/5#discussioncomment-1144935)_

In this project, I see:
1. You should rename the package
2. Add all media in the assets file to easy manage
3. Replace link directed in your code like that: ./assets/background.png
4. Make an issue for look for help from your community
5. Delete final line in code and use refactor to analyze code
6. Run code together with CI pipeline workflow.
--> Hope that will useful for you. Thanh you!

**Comment by thuongtruong1009** [comment]
@all-contributors please add @font-end-pro for the great issue and idea contributing

**Comment by thuongtruong1009** [comment]
@all-contributors please add @thuongtruong1009 for the author of code, algorithm, idea, run and push code

**Comment by thuongtruong1009** [comment]
@all-contributors please add @ImgBotApp for the health of image pixel

**Comment by thuongtruong1009** [comment]
@all-contributors please add @ImgBotApp for the data and tool

**Comment by thuongtruong1009** [comment]
@all-contributors please add @0826240270 for the great issue and idea contributing

**Comment by thuongtruong1009** [comment]
@all-contributors please add @tung01673641696 for the great issue and idea contributing

**Comment by thuongtruong1009** [comment]
@all-contributors please add @codacy-badger for the test, bug, data

**Comment by thuongtruong1009** [comment]
@all-contributors please add @codacy-badger for the test, bug, data

**Comment by thuongtruong1009** [comment]
@all-contributors please add @wpolancofor the ideas, a11y

**Comment by thuongtruong1009** [comment]
@all-contributors please add @wpolanco for the ideas, a11y

**Comment by thuongtruong1009** [comment]
@all-contributors please add @Sanjulata19 for the ideas, mentoring and discuss

**Comment by thuongtruong1009** [comment]
@all-contributors please add @Oopprojectgame for doc and example
